### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'frames'

### ISSUE THREAD

**Issue by pansanity666** [visinf/dense-ulearn-vos#8]
In ``infer_vos.py``, Line 211 and 237, I've got the ``TypeError: forward() missing 1 required positional argument: 'frames' ``, after I change them as keyward arguments (frames=frames[:1]),  the error solved. Is it a bug or something related to my environment? I haven't found the reason yet since the frames is not a keyward arguments in ``framework.py ``

By the way, does your evaluation script support Multi-GPU inference? It seems that inference on YouTube-VOS will take a very long time ?

Best,

**Comment by arnike** [comment]
Hi and sorry for a very late reply.
Did you make any changes to the original code prior to getting this error? Otherwise it's hard say.
Regarding the YouTube-VOS evaluation -- it is indeed quite time consuming. Currently implementation is only single GPU, but could be potentially extended. You'd only need to be careful with i/o throughput, especially if you're saving visualisations.

Best regards, Nikita
